version: "3"
services:
  apache:
    build: .
    image: xhprof-demo
    container_name: xhprof-demo
    ports:
      - 8080:80
      - 8081:8080
    volumes:
      - ./index.php:/var/www/html/index.php
